version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: survey-project-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DB}
    volumes:
      - survey-data:/var/lib/mysql
    ports:
      - "3306:3306"

  web:
    build: .
    container_name: survey-project-web
    depends_on:
      - mysql
    environment:
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DB=${MYSQL_DB}
    ports:
      - "80:5000"   # dışarıdan 80, container içinde 5000

volumes:
  survey-data:
